# Generated by Django 3.0.5 on 2025-04-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_mcqs',
        ),
    ]
