# Generated by Django 3.0.5 on 2025-04-04 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_question_num_mcqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], default='Option1', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Default Option 1', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Default Option 2', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Default Option 3', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='Default Option 4', max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.Question'),
        ),
    ]
