# Generated by Django 3.0.5 on 2025-04-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20250404_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_text1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='question_type1',
        ),
    ]
