# Generated by Django 3.0.5 on 2025-04-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20250404_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
